spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orm_practice
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create